services:
  - type: web
    name: botnet-controller
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python botnet_controller.py
    envVars:
      - key: BOT_TOKEN
        value: 8928657652:AAFmDv6nlNcoxqKtB2gmcZ1kyvnjj5rd2A8
      - key: ADMIN_ID
        value: 8003369858
    ports:
      - port: 5000
